const constants = {
  PROGRESS: "PROGRESS",
  SIGNIN: "SIGNIN",
  SIGNUP: "SIGNUP",
  SIGNIN_SUCESS: "SIGNIN_SUCESS",
  SIGNIN_FAILED: "SIGNIN_FAILED",
  SIGNUP_PROGRESS: "SIGNUP_PROGRESS",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILED: "SIGNUP_FAILED",
  ADD_TODO: "ADD_TODO",
  EDIT_TODO: "EDIT_TODO",
  DELETE_TODO: "DELETE_TODO",
  MODAL_SHOW: "MODAL_SHOW",
  MODAL_CLOSE: "MODAL_CLOSE",
  EDIT_MODE: "EDIT_MODE",
  TODO_APP_STATE: "TODO_APP_STATE",
};

export default constants;
